// Command gentable writes shape/table.go: the shape vector of every printable
// ASCII glyph in libcaca's built-in Monospace 9 font. Run it with
// `go generate ./shape`.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strconv"

	"github.com/0magnet/img2txt-go/caca"
)

func main() {
	f, err := caca.BuiltinFont("Monospace 9")
	if err != nil {
		log.Fatal(err)
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by shape/internal/gentable from libcaca's Monospace 9 font. DO NOT EDIT.\n\n")
	b.WriteString("package shape\n\n")
	b.WriteString("// ASCII holds the normalized shape vector of each printable ASCII glyph.\n")
	b.WriteString("var ASCII = []Entry{\n")
	for _, e := range caca.ShapeEntries(f) {
		fmt.Fprintf(&b, "\t{%s, Vector{", strconv.QuoteRune(e.R))
		for i, v := range e.V {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(strconv.FormatFloat(v, 'f', 6, 64))
		}
		b.WriteString("}},\n")
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("table.go", src, 0o644); err != nil { //nolint:gosec // a source file
		log.Fatal(err)
	}
}
