package caca

import (
	"bytes"
	"image"
	"image/color"
	"image/png"
	"strings"
	"testing"
)

// testImage builds a small deterministic gradient and returns the decoded
// bitmap plus its dither.
func testImage(t *testing.T, w, h int) *Image {
	t.Helper()
	src := image.NewNRGBA(image.Rect(0, 0, w, h))
	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			src.SetNRGBA(x, y, color.NRGBA{
				R: uint8(x * 255 / max(w-1, 1)),
				G: uint8(y * 255 / max(h-1, 1)),
				B: uint8((x + y) * 255 / max(w+h-2, 1)),
				A: 255,
			})
		}
	}
	var buf bytes.Buffer
	if err := png.Encode(&buf, src); err != nil {
		t.Fatalf("encode: %v", err)
	}
	im, err := DecodeImage(&buf)
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	return im
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}

// render dithers the image onto a canvas of the given size.
func render(t *testing.T, im *Image, cols, lines int, algo string) *Canvas {
	t.Helper()
	cv := NewCanvas(cols, lines)
	cv.SetColorANSI(Default, Transparent)
	cv.Clear()
	if !im.Dither.SetAlgorithm(algo) {
		t.Fatalf("unknown algorithm %q", algo)
	}
	cv.DitherBitmap(0, 0, cols, lines, im.Dither, im.Pixels)
	return cv
}

// TestExportFormats checks that every format produces plausible, non-empty
// output.
func TestExportFormats(t *testing.T) {
	im := testImage(t, 32, 24)
	cv := render(t, im, 20, 10, "fstein")

	for _, e := range ExportList() {
		format := e[0]
		out, ok := cv.Export(format)
		if !ok {
			t.Errorf("format %q not supported", format)
			continue
		}
		if len(out) == 0 {
			t.Errorf("format %q produced no output", format)
		}
	}
}

// TestTGA checks the TGA header and that the canvas rasterises to the font's
// glyph dimensions.
func TestTGA(t *testing.T) {
	im := testImage(t, 32, 24)
	cv := render(t, im, 20, 10, "fstein")

	out, ok := cv.Export("tga")
	if !ok {
		t.Fatal("tga export failed")
	}
	f, err := LoadFont(mono9Data)
	if err != nil {
		t.Fatalf("load font: %v", err)
	}
	w, h := cv.Width*f.Width(), cv.Height*f.Height()
	if len(out) != 18+w*h*4 {
		t.Errorf("tga size = %d, want %d", len(out), 18+w*h*4)
	}
	if out[2] != 2 {
		t.Errorf("image type = %d, want 2 (uncompressed truecolour)", out[2])
	}
	if out[16] != 32 {
		t.Errorf("pixel depth = %d, want 32", out[16])
	}
	if gotW := int(out[12]) | int(out[13])<<8; gotW != w {
		t.Errorf("tga width = %d, want %d", gotW, w)
	}
	if gotH := int(out[14]) | int(out[15])<<8; gotH != h {
		t.Errorf("tga height = %d, want %d", gotH, h)
	}
}

// TestLoadFont checks the built-in font parses with the expected geometry.
func TestLoadFont(t *testing.T) {
	f, err := LoadFont(mono9Data)
	if err != nil {
		t.Fatalf("load font: %v", err)
	}
	if f.Width() != 7 || f.Height() != 15 {
		t.Errorf("font geometry = %dx%d, want 7x15", f.Width(), f.Height())
	}
	if f.header.bpp != 4 {
		t.Errorf("font bpp = %d, want 4", f.header.bpp)
	}
	if _, err := LoadFont([]byte("short")); err == nil {
		t.Error("truncated font data should fail to load")
	}
}

// TestExportMarkers checks format-specific structure.
func TestExportMarkers(t *testing.T) {
	im := testImage(t, 32, 24)
	cv := render(t, im, 20, 10, "fstein")

	tests := []struct {
		format string
		want   []string
	}{
		{"html", []string{"<!DOCTYPE html PUBLIC", "Generated by libcaca " + Version, "<br />", "</div></body></html>"}},
		{"html3", []string{"<table border=\"0\"", "<tr>", "<tt>", "</table>"}},
		{"svg", []string{"<?xml version=\"1.0\"", "<svg width=\"120\" height=\"100\"", "</svg>"}},
		{"ps", []string{"%!\n", "csquare", "showpage"}},
		{"troff", []string{".nf\n", "\\m[", "\\M["}},
		{"bbfr", []string{"[font=Courier New]", "[/font]"}},
	}
	for _, tt := range tests {
		out, ok := cv.Export(tt.format)
		if !ok {
			t.Fatalf("format %q unsupported", tt.format)
		}
		s := string(out)
		for _, want := range tt.want {
			if !strings.Contains(s, want) {
				t.Errorf("%s output missing %q", tt.format, want)
			}
		}
	}
}

// TestANSIWidth80 checks the special line terminator libcaca emits when the
// canvas is exactly 80 columns wide.
func TestANSIWidth80(t *testing.T) {
	im := testImage(t, 32, 24)

	cv80 := render(t, im, 80, 4, "fstein")
	out, _ := cv80.Export("ansi")
	if !bytes.Contains(out, []byte("\033[s\n\033[u")) {
		t.Error("80-column ANSI export should use the save/restore cursor terminator")
	}

	cv40 := render(t, im, 40, 4, "fstein")
	out, _ = cv40.Export("ansi")
	if !bytes.Contains(out, []byte("\033[0m\r\n")) {
		t.Error("non-80-column ANSI export should reset and use CRLF")
	}
}

// TestDitherAlgorithms checks that each algorithm renders and that the ordered
// ones differ from undithered output.
func TestDitherAlgorithms(t *testing.T) {
	im := testImage(t, 40, 30)
	var none []byte
	for _, e := range AlgorithmList() {
		algo := e[0]
		cv := render(t, im, 24, 12, algo)
		out, ok := cv.Export("ansi")
		if !ok || len(out) == 0 {
			t.Fatalf("algorithm %q produced no output", algo)
		}
		if algo == "none" {
			none = out
		} else if algo == "ordered8" && bytes.Equal(out, none) {
			t.Error("ordered8 output should differ from undithered output")
		}
	}
}

// TestAlphaTransparent checks that fully transparent pixels leave cells at the
// canvas default rather than dithering them.
func TestAlphaTransparent(t *testing.T) {
	w, h := 16, 16
	src := image.NewNRGBA(image.Rect(0, 0, w, h))
	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			src.SetNRGBA(x, y, color.NRGBA{R: 255, G: 0, B: 0, A: 0})
		}
	}
	var buf bytes.Buffer
	if err := png.Encode(&buf, src); err != nil {
		t.Fatal(err)
	}
	im, err := DecodeImage(&buf)
	if err != nil {
		t.Fatal(err)
	}
	cv := render(t, im, 8, 4, "fstein")
	for i, ch := range cv.Chars {
		if ch != ' ' {
			t.Fatalf("cell %d should stay blank for a fully transparent image, got %q", i, ch)
		}
	}
}

// TestCP437Roundtrip checks the charset tables.
func TestCP437Roundtrip(t *testing.T) {
	for b := 0x20; b < 0x100; b++ {
		r := CP437ToUTF32(byte(b))
		if r == 0 {
			continue
		}
		if got := UTF32ToCP437(r); got != byte(b) {
			t.Errorf("round trip failed for 0x%02x: got 0x%02x", b, got)
		}
	}
}

// TestAttrConversion spot-checks the attribute helpers.
func TestAttrConversion(t *testing.T) {
	cv := NewCanvas(1, 1)
	cv.SetColorANSI(Red, Blue)
	attr := cv.Attr()
	if got := AttrToANSIFg(attr); got != Red {
		t.Errorf("fg = %d, want %d", got, Red)
	}
	if got := AttrToANSIBg(attr); got != Blue {
		t.Errorf("bg = %d, want %d", got, Blue)
	}
	if got := AttrToRGB12Fg(attr); got != ansitab16[Red]&0x0fff {
		t.Errorf("rgb12 fg = %03x", got)
	}
}

// TestMask2Shift checks the shifts derived from the ARGB masks img2txt uses.
func TestMask2Shift(t *testing.T) {
	if r, l := mask2shift(0x00ff0000); r != 16 || l != 4 {
		t.Errorf("red mask shifts = %d,%d want 16,4", r, l)
	}
	if r, l := mask2shift(0x000000ff); r != 0 || l != 4 {
		t.Errorf("blue mask shifts = %d,%d want 0,4", r, l)
	}
	if r, l := mask2shift(0); r != 0 || l != 0 {
		t.Errorf("zero mask shifts = %d,%d want 0,0", r, l)
	}
}
